"""
Validation pipeline + first baseline model for the nuclear waste temperature project.

Run from the repository root:
    python src/train_baseline.py

Requires that cleaning has already been run:
    python src/cleaning.py

Input:
    data/processed/train_cleaned.parquet
    data/processed/test_with_features.parquet

Outputs:
    reports/baseline_metrics.csv
    reports/validation_predictions_sample.csv
    models/baseline_hist_gradient_boosting.joblib
    submissions/baseline_submission.csv
"""

from __future__ import annotations

from pathlib import Path
import warnings

import numpy as np
import pandas as pd

from sklearn.ensemble import HistGradientBoostingRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from sklearn.model_selection import GroupShuffleSplit, train_test_split
from sklearn.inspection import permutation_importance
import joblib


# -----------------------------
# Configuration
# -----------------------------
REPO_ROOT = Path(__file__).resolve().parents[1]
PROCESSED_DIR = REPO_ROOT / "data" / "processed"
REPORTS_DIR = REPO_ROOT / "reports"
MODELS_DIR = REPO_ROOT / "models"
SUBMISSIONS_DIR = REPO_ROOT / "submissions"

for folder in [REPORTS_DIR, MODELS_DIR, SUBMISSIONS_DIR]:
    folder.mkdir(parents=True, exist_ok=True)

RANDOM_STATE = 42
VALIDATION_SENSOR_FRACTION = 0.20

# To keep the first baseline fast enough on a laptop.
# You can increase these later if the script runs comfortably.
MAX_TRAIN_ROWS_FOR_VALIDATION = 600_000
MAX_VAL_ROWS_FOR_VALIDATION = 300_000
MAX_TRAIN_ROWS_FOR_FINAL_MODEL = 1_000_000

TARGET = "temperature"

# Numeric features generated by cleaning.py.
# The script will automatically keep only the ones that exist.
FEATURE_COLUMNS = [
    "time",
    "power",
    "coor_x",
    "coor_y",
    "coor_z",
    "time_years",
    "r_xy",
    "r_xyz",
    "abs_y",
    "power_x_time",
    "power_over_r_xy",
]


# -----------------------------
# Utility functions
# -----------------------------
def load_processed_data() -> tuple[pd.DataFrame, pd.DataFrame]:
    train_path = PROCESSED_DIR / "train_cleaned.parquet"
    test_path = PROCESSED_DIR / "test_with_features.parquet"

    if not train_path.exists():
        raise FileNotFoundError(
            f"Missing {train_path}. Run the cleaning step first: python src/cleaning.py"
        )
    if not test_path.exists():
        raise FileNotFoundError(
            f"Missing {test_path}. Run the cleaning step first: python src/cleaning.py"
        )

    train = pd.read_parquet(train_path)
    test = pd.read_parquet(test_path)
    return train, test


def get_feature_columns(train: pd.DataFrame, test: pd.DataFrame) -> list[str]:
    usable = [c for c in FEATURE_COLUMNS if c in train.columns and c in test.columns]
    missing = sorted(set(FEATURE_COLUMNS) - set(usable))

    if missing:
        print(f"Warning: these expected features are missing and will be ignored: {missing}")

    if not usable:
        raise ValueError("No usable feature columns found. Check cleaning.py output columns.")

    return usable


def downsample(df: pd.DataFrame, max_rows: int, random_state: int) -> pd.DataFrame:
    if len(df) <= max_rows:
        return df
    return df.sample(n=max_rows, random_state=random_state)


def create_sensor_validation_split(train: pd.DataFrame) -> tuple[pd.DataFrame, pd.DataFrame]:
    """
    Split by sensor, not by random rows.

    Why this is better for this project:
    - the goal is to predict temperatures at locations where there are no sensors
    - holding out full sensors tests spatial generalization better than random rows
    """
    if "sensor" not in train.columns or train["sensor"].nunique() < 5:
        warnings.warn(
            "Could not create a sensor-based split. Falling back to random row split."
        )
        train_part, val_part = train_test_split(
            train, test_size=VALIDATION_SENSOR_FRACTION, random_state=RANDOM_STATE
        )
        return train_part, val_part

    splitter = GroupShuffleSplit(
        n_splits=1,
        test_size=VALIDATION_SENSOR_FRACTION,
        random_state=RANDOM_STATE,
    )

    train_idx, val_idx = next(
        splitter.split(train, groups=train["sensor"])
    )

    train_part = train.iloc[train_idx].copy()
    val_part = train.iloc[val_idx].copy()
    return train_part, val_part


def make_model() -> HistGradientBoostingRegressor:
    """A strong but simple first baseline available in scikit-learn."""
    return HistGradientBoostingRegressor(
        loss="squared_error",
        learning_rate=0.08,
        max_iter=250,
        max_leaf_nodes=31,
        l2_regularization=0.01,
        early_stopping=True,
        validation_fraction=0.10,
        random_state=RANDOM_STATE,
    )


def evaluate_predictions(y_true: pd.Series, y_pred: np.ndarray) -> dict[str, float]:
    mse = mean_squared_error(y_true, y_pred)
    rmse = np.sqrt(mse)
    mae = mean_absolute_error(y_true, y_pred)
    r2 = r2_score(y_true, y_pred)
    return {
        "rmse": rmse,
        "mae": mae,
        "r2": r2,
    }


def save_submission(test: pd.DataFrame, predictions: np.ndarray) -> Path:
    """
    Save a first Kaggle-style submission.

    If the test file contains an ID column, use it.
    Otherwise create an Id column from the row number.
    You may need to rename columns later depending on the Kaggle sample submission format.
    """
    id_candidates = ["id", "Id", "ID", "sample_id", "row_id"]
    id_col = next((c for c in id_candidates if c in test.columns), None)

    if id_col is not None:
        submission = pd.DataFrame({id_col: test[id_col].to_numpy(), TARGET: predictions})
    else:
        submission = pd.DataFrame({"Id": np.arange(len(test)), TARGET: predictions})

    output_path = SUBMISSIONS_DIR / "baseline_submission.csv"
    submission.to_csv(output_path, index=False)
    return output_path


# -----------------------------
# Main pipeline
# -----------------------------
def main() -> None:
    print("Loading processed data...")
    train, test = load_processed_data()
    print(f"Cleaned train shape: {train.shape}")
    print(f"Processed test shape: {test.shape}")

    features = get_feature_columns(train, test)
    print(f"Using features: {features}")

    # Drop any remaining rows with missing values in features/target.
    train = train.dropna(subset=features + [TARGET]).copy()
    test_features = test[features].copy()

    if test_features.isna().any().any():
        print("Warning: test has missing feature values. Filling with training medians.")
        medians = train[features].median(numeric_only=True)
        test_features = test_features.fillna(medians)

    print("Creating sensor-based validation split...")
    train_part, val_part = create_sensor_validation_split(train)
    print(f"Train split shape: {train_part.shape}")
    print(f"Validation split shape: {val_part.shape}")
    if "sensor" in train.columns:
        print(f"Train sensors: {train_part['sensor'].nunique()}")
        print(f"Validation sensors: {val_part['sensor'].nunique()}")

    # Downsample for laptop-friendly first baseline.
    train_fit = downsample(train_part, MAX_TRAIN_ROWS_FOR_VALIDATION, RANDOM_STATE)
    val_eval = downsample(val_part, MAX_VAL_ROWS_FOR_VALIDATION, RANDOM_STATE)

    X_train = train_fit[features]
    y_train = train_fit[TARGET]
    X_val = val_eval[features]
    y_val = val_eval[TARGET]

    print("Training baseline model...")
    model = make_model()
    model.fit(X_train, y_train)

    print("Evaluating on validation set...")
    val_pred = model.predict(X_val)
    metrics = evaluate_predictions(y_val, val_pred)
    metrics_df = pd.DataFrame([metrics])
    metrics_path = REPORTS_DIR / "baseline_metrics.csv"
    metrics_df.to_csv(metrics_path, index=False)

    print("\nValidation metrics:")
    for key, value in metrics.items():
        print(f"  {key}: {value:.5f}")
    print(f"Saved metrics to: {metrics_path}")

    # Save a small sample of validation predictions for manual inspection.
    val_preview = val_eval[[c for c in ["sensor", "time", "power", "coor_x", "coor_y", "coor_z", TARGET] if c in val_eval.columns]].copy()
    val_preview["prediction"] = val_pred
    val_preview["error"] = val_preview["prediction"] - val_preview[TARGET]
    val_preview_path = REPORTS_DIR / "validation_predictions_sample.csv"
    val_preview.head(50_000).to_csv(val_preview_path, index=False)
    print(f"Saved validation prediction sample to: {val_preview_path}")

    # Optional feature importance on a smaller validation sample.
    print("Computing permutation feature importance on a small sample...")
    importance_sample = val_eval.sample(n=min(20_000, len(val_eval)), random_state=RANDOM_STATE)
    result = permutation_importance(
        model,
        importance_sample[features],
        importance_sample[TARGET],
        n_repeats=3,
        random_state=RANDOM_STATE,
        scoring="neg_root_mean_squared_error",
    )
    importance_df = pd.DataFrame({
        "feature": features,
        "importance_mean": result.importances_mean,
        "importance_std": result.importances_std,
    }).sort_values("importance_mean", ascending=False)
    importance_path = REPORTS_DIR / "baseline_feature_importance.csv"
    importance_df.to_csv(importance_path, index=False)
    print(f"Saved feature importance to: {importance_path}")

    # Train final baseline on a larger sample of all cleaned train data.
    print("Training final baseline model on cleaned data sample...")
    final_train = downsample(train, MAX_TRAIN_ROWS_FOR_FINAL_MODEL, RANDOM_STATE)
    final_model = make_model()
    final_model.fit(final_train[features], final_train[TARGET])

    model_path = MODELS_DIR / "baseline_hist_gradient_boosting.joblib"
    joblib.dump({"model": final_model, "features": features}, model_path)
    print(f"Saved model to: {model_path}")

    print("Predicting test set...")
    test_predictions = final_model.predict(test_features)
    submission_path = save_submission(test, test_predictions)
    print(f"Saved first submission to: {submission_path}")

    print("\nBaseline pipeline complete.")


if __name__ == "__main__":
    main()
